services:
  db:
    image: mysql:8.0
    container_name: wella-lms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YourPassword
      MYSQL_DATABASE: wella_lms
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
